name: Github Actions
on: 
  push:
    branches: ['**']
  schedule:
    - cron: '5 4 * * 6'
env:
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:

  js-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106
    # runs-on: ${{ matrix.os }}
    # timeout-minutes: 20
    # strategy:
    #   fail-fast: false # don't kill tests when one environment fails
    #   matrix:
    #     os: [ubuntu-latest, windows-2022, macOS-latest]
    name: Build & Tests
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.413
    - name: yarn install
      run: yarn --cwd frontend install --frozen-lockfile
    - name: TypeScript check
      run: yarn --cwd frontend tsc-check
    - name: yarn build
      run: yarn --cwd frontend build
    - name: Svelte Check
      run: yarn --cwd frontend svelte-check --threshold warning
    - name: jest (unit tests)
      run: yarn --cwd frontend jest --ci --reporters=default --reporters=jest-github-actions-reporter
    - name: dotnet build
      run: dotnet build server/Ksp.WebServer/
    - name: Cypress (UI tests)
      uses: cypress-io/github-action@v4
      with:
        install-command: yarn --frozen-lockfile --silent
        browser: chrome  # for some weird reason, cypress does not detect FF in the container :(
        working-directory: ./frontend
        start: yarn start

  old-node-build:
    runs-on: ubuntu-latest
    name: Build on old Node.js
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: yarn install
      run: yarn --cwd frontend install --frozen-lockfile
    - name: yarn build
      run: yarn --cwd frontend build
