name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd ./frontend install --frozen-lockfile # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd ./frontend jest # will run `yarn jest` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd ./frontend cypress run
